---
- name: Configuración de servidores
  hosts: all
  become: yes
  tasks:
    - name: Actualizar cache de software de apt
      apt:
        update_cache: yes

    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear archivo
      file:
        path: /tmp/EliezerMejia.txt
        state: touch

    - name: Copiar archivo local al servidor
      copy:
        src: ./ArchivoLocal.txt 
        dest: /tmp/ArchivoLocal.txt 

    - name: Crear carpeta
      file:
        path: "/tmp/Aplicacion"
        state: directory

    - name: Iniciar el servicio de apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Agregar un usuario al servidor
      user:
        name: NuevoUsuario
        state: present

    - name: Ejecutar un script en el servidor
      script: ./script.sh
